# Site settings
title:          "dansheffler.com"
author:         "Dan Sheffler"
email:          ""
description:    "The personal website of Dan Sheffler"
baseurl:        "http://www.dansheffler.com"
url:            "http://www.dansheffler.com"
future:         false
excerpt_separator: <!--more-->
plugins:        [jekyll-pandoc, jekyll-gist]

# lunr_search:
#   excludes: [sitemap.xml,index.html,search,archive,papers,share,teaching]

# Build settings
markdown:       Pandoc
pandoc:
    extensions:
        - from: markdown+smart
        - bibliography: $BIBLIO
        - csl: $CSL
        - mathjax
markdown_ext:   markdown,mkdown,mkdn,mkd,md
permalink:      /blog/:year-:month-:day-:title/
encoding:       utf-8

# incremental: true

collections:
  papers:
    output: true
  share:
    output: true
  teaching:
    output: true
  presentations:
    output: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts" # overrides previous default layout
  -
    scope:
      path: ""
      type: "presentations"
    values:
      layout: "presentation"
