# Site settings
title:          "dansheffler.com"
author:         "Dan Sheffler"
email:          ""
description:    "The personal website of Dan Sheffler"
baseurl:        ""
url:            "http://www.dansheffler.com"
paginate:       10
paginate_path:  "/page:num"
future:         false

# lunr_search:
#   excludes: [sitemap.xml,index.html,search,archive,papers,share,teaching]

# Build settings
markdown:       pandoc
pandoc:
    extensions:
        - smart
        - bibliography="C:\\Users\\Dan\\Dropbox\\Jabref\\mybib.bib"
        - csl="C:\\Users\\Dan\\Dropbox\\Pandoc\\default.csl"
        - mathjax
markdown_ext:   markdown,mkdown,mkdn,mkd,md
permalink:      /blog/:year-:month-:day-:title
encoding:       utf-8

collections:
  papers:
    output: true
  share:
    output: true
  teaching:
    output: true
  presentations:
    output: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post" # overrides previous default layout
  -
    scope:
      path: ""
      type: "presentations"
    values:
      layout: "presentation"
